### PR TITLE
Add ability to genarate some comments

### PR DESCRIPTION
**Pull request by Bcow7**
Hi,

I added the ability to generate some comments with big fonts and the possibility to choose the comment style (None, #, //, /*  */).

Do you want to merge my modifications with your repo and publish an update for Package Control?

Cheers,
Flo

### CODE REVIEW

**Comment by adamchainz** [comment]
IIRC when I started creating this plugin I had the idea of doing comments. Sublime has two commands to comment the current selection using the syntax of the current language, bound on Mac to `cmd-/` (single line comments) and `cmd-alt-/` (multi-line comments, if the current language has them).

Because there are two styles per language, and because I found it hard to invoke that as a step in the plugin (maybe it's not though!), I didn't add the comment command. I did make it leave the text selected though so that it's only one more key press away - and you can choose which style too.

I think this PR does is less preferable to directly invoking the comment commands. Perhaps they should be documented in the plugin, or even a separate figlet command added to invoke them; but adding another setting that requires the user to input "how comments are done", despite Sublime already knowing this on a per-language basis, feels like a complication to me.

Thoughts?

**Comment by Bcow7** [comment]
Hi Adam,

Yes, you're right! We could use something like that : 

```
view.sel().add(sublime.Region(cursor, cursor + len(text)))
self.window.run_command('toggle_comment', {'block': True})
```

I wrote this code because I like to have a frame around my Big Fonts ;-)
You can ignore this PR, it was just a suggestion...

**Comment by adamchainz** [comment]
If you want to open a new PR for commented text, go ahead. Another idea I've had is that it could be an option that 'add text' automatically adds comments. Unsure what the best way is now.

**Comment by Bcow7** [comment]
It is the case of this PR. You set the option and then it generates piglet and it automatically adds comments.

But maybe you're  right, we could only add a standard block comment

**Comment by adamchainz** [comment]
Documented adding comments in 0f4f86ed256299bc2f3121036212ee0f361ebbe9 ⚡️

**Pull request closed without merging**
